### PR TITLE
Additional changes and cleanup

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by lunny** [comment]
trusted LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by metalmatze** [comment]
But why did you drop the 404 entirely? No reason for that. I didn't had any translations.

**Comment by tboerger** [comment]
The 404 page gets generated once, with the last language (Chinese) that's why I dropped it and I would keep the default 404 error page of the Webserver

**Comment by lunny** [comment]
We could keep 404 an english words. Only one 404 is OKay.

**Comment by tboerger** [comment]
Currently it gets only translated to chinese, that's why I have dropped it for now.

**Pull request merged**
