### PR TITLE
Move disqus to be part of the content

### PR DESCRIPTION
**Pull request by metalmatze**
Disqus should be part of the content. It's tightly coupled to the content.
This moves disqus in the same column as the content and thus has the same width.
Otherwise it'll just look off. 😊

### CODE REVIEW

**Comment by tboerger** [comment]
But it should still get into a separate row tag.

**Comment by andreynering** [comment]
LGTM

**Comment by metalmatze** [comment]
No, I don't think there's a reason for disqus to be in a new row. I would be anyway a `.row` within the column that the content is. It should be aligned just like the content and for that we don't need it to be in its on grid.
It's just another `<div>` below the content.

**Comment by tboerger** [comment]
Sorry, have done that by accident directly to master...

**Pull request closed without merging**
