### PR TITLE
Open downloads in new tab until we got a better layout

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by metalmatze** [comment]
I generally dislike forcing the user to open a new tab. I wanted to create a PR to remove the one on the github link. If I want to open in a new tab I can use shortcuts. But if I want to simply go back in the browser history from dl or github I currently  can't...

**Comment by tboerger** [comment]
But dl and github are leaving the page, there i personally prefer a new tab. But whatever the majority decides...

**Pull request merged**
