### PR TITLE
Include internal disqus template

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by Bwko** [comment]
LGTM

**Comment by andreynering** [comment]
LGTM

**Comment by metalmatze** [comment]
> We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

Something seems broken? Or are there some keys missing? Idk.

Nevertheless I think that the iframe for disqus should be place in the same container as the content, to be as big as the content itself. Otherwise it'll look off. 😕

**Comment by lunny** [comment]
`Failed to load resource: net::ERR_CERT_DATABASE_CHANGED`, @metalmatze do you encounter the same problem?

**Comment by tboerger** [comment]
I think it's related to the url generated by Hugo. Should be fixed with my pending prs for website and docs at least. Blog and code is not finished yet

**Pull request merged**
